# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

from pyspark.sql.functions import col

EH_NAMESPACE = "wikimedia-producer"
EH_NAME = "wikimedia-stream"

EH_CONN_STR = "Endpoint=sb://wikimedia-producer.servicebus.windows.net/;SharedAccessKeyName=databricks;SharedAccessKey=6UEY80QSBCzxVqV8XE26QR4arXLKLD+Id+AEhBInWwY=;EntityPath=wikimedia-stream"

KAFKA_OPTIONS = {
  "kafka.bootstrap.servers": f"{EH_NAMESPACE}.servicebus.windows.net:9093",
  "subscribe": EH_NAME,
  "kafka.sasl.mechanism": "PLAIN",
  "kafka.security.protocol": "SASL_SSL",
  "kafka.sasl.jaas.config":
    f'org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="{EH_CONN_STR}";',
  "startingOffsets": "earliest"
}

df = spark.readStream.format("kafka") \
    .options(**KAFKA_OPTIONS) \
    .load()

df_transformed = df.select(
    col("value").cast("string").alias("body"),
    col("timestamp"),
    col("offset"),
    col("partition"),
    col("topic")
)

df_transformed.writeStream \
    .format("delta") \
    .outputMode("append") \
    .option("checkpointLocation", "/Volumes/wikimedia/wiki/checkpoint_vol") \
    .trigger(availableNow= True)\
    .table("wikimedia.wiki.bronze_wikimedia")

# COMMAND ----------

